name: swarmcg
channels:
  - conda-forge
dependencies:
  - cycler
  - dscribe
  - matplotlib
  - mdanalysis
  - mypy
  - numpy
  - pandas
  - pip
  - pybind11
  - pyemd
  - pylint
  - pytest
  - pytest-runner
  - python
  - scikit-learn
  - scipy
  - setuptools
  - wheel
  - pip:
      - fst-pso
